<?php
namespace App\Exports;

use App\Models\CensusFile;
use Maatwebsite\Excel\Concerns\FromCollection;

class CensusFileExport implements FromCollection
{
    protected $searchCriteria;

    public function __construct(array $searchCriteria)
    {
        $this->searchCriteria = $searchCriteria;
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    public function collection()
    {
        return CensusFile::filterByCriteria($this->searchCriteria)->get();
    }


    public function headings(): array
    {
        return [
        'id',
      'DOT_NUMBER',
      'NAME',
      'NAME_DBA',
      'ACT_STAT',
      'CARSHIP',
      'DBNUM',
      'PHY_NATN',
      'REG',
      'PHY_STR',
      'PHY_CITY',
      'PHY_CNTY',
      'PHY_ST',
      'PHY_ZIP',
      'UNDELIV_PHY',
      'TEL_NUM',
      'CELL_NUM',
      'FAX_NUM',
      'MAI_NATN',
      'MAI_STR',
      'MAI_CITY',
      'MAI_CNTY',
      'MAI_ST',
      'MAI_ZIP',
      'UNDELIV_MAI',
      'OIC',
      'TERR',
      'ICC_DOCKET_1_PREFIX',
      'ICC1',
      'ICC_DOCKET_2_PREFIX',
      'ICC2',
      'ICC_DOCKET_3_PREFIX',
      'ICC3',
      'class',
      'classdef',
      'CRRINTER',
      'CRRHMINTRA',
      'CRRINTRA',
      'SHPINTER',
      'SHPINTRA',
      'VEHICLE_REGISTRANT',
      'ORG',
      'GENFREIGHT',
      'HOUSEHOLD',
      'METALSHEET',
      'MOTORVEH',
      'DRIVETOW',
      'LOGPOLE',
      'BLDGMAT',
      'MOBILEHOME',
      'MACHLRG',
      'PRODUCE',
      'LIQGAS',
      'INTERMODAL',
      'PASSENGERS',
      'OILFIELD',
      'LIVESTOCK',
      'GRAINFEED',
      'COALCOKE',
      'MEAT',
      'GARBAGE',
      'USMAIL',
      'CHEM',
      'DRYBULK',
      'COLDFOOD',
      'BEVERAGES',
      'PAPERPROD',
      'UTILITY',
      'FARMSUPP',
      'CONSTRUCT',
      'WATERWELL',
      'CARGOOTHR',
      'OTHERCARGO',
      'HM_IND',
      'OWNTRUCK',
      'OWNTRACT',
      'OWNTRAIL',
      'OWNCOACH',
      'OWNSCHOOL_1_8',
      'OWNSCHOOL_9_15',
      'OWNSCHOOL_16',
      'OWNBUS_16',
      'OWNVAN_1_8',
      'OWNVAN_9_15',
      'OWNLIMO_1_8',
      'OWNLIMO_9_15',
      'OWNLIMO_16',
      'TRMTRUCK',
      'TRMTRACT',
      'TRMTRAIL',
      'TRMCOACH',
      'TRMSCHOOL_1_8',
      'TRMSCHOOL_9_15',
      'TRMSCHOOL_16',
      'TRMBUS_16',
      'TRMVAN_1_8',
      'TRMVAN_9_15',
      'TRMLIMO_1_8',
      'TRMLIMO_9_15',
      'TRMLIMO_16',
      'TRPTRUCK',
      'TRPTRACT',
      'TRPTRAIL',
      'TRPCOACH',
      'TRPSCHOOL_1_8',
      'TRPSCHOOL_9_15',
      'TRPSCHOOL_16',
      'TRPBUS_16',
      'TRPVAN_1_8',
      'TRPVAN_9_15',
      'TRPLIMO_1_8',
      'TRPLIMO_9_15',
      'TRPLIMO_16',
      'TOT_TRUCKS',
      'TOT_BUSES',
      'TOT_PWR',
      'FLEETSIZE',
      'INTERLT100',
      'INTERGT100',
      'INTER_DRS',
      'INTRALT100',
      'INTRAGT100',
      'INTRA_DRS',
      'AVG_TLD',
      'TOT_DRS',
      'CDL_DRS',
      'REVTYPE',
      'REVDOCNUM',
      'REVDATE',
      'ACC_RATE',
      'REPPREVRAT',
      'MLG150',
      'MLG151',
      'RATING',
      'RATEDATE',
      'PHY_BARRIO',
      'MAI_BARRIO',
      'MCSIPSTEP',
      'MCSIPDATE',
      'USERID',
      'ADDCODE',
      'UPD_REAS',
      'DELCODE',
      'MCS150MILEAGEYEAR',
      'ADDDATE',
      'CHGNDATE',
      'DELDATE',
      'TOT_CARS',

      'VERSION',
      'CREATEDATE',
      'ADDUSERID',
      'DELUSERID',
      'MCS_150_DATE',
      'REC_UPDATE_FLAG',
      'EMAILADDRESS',
      'USDOT_REVOKED_FLAG',
      'USDOT_REVOKED_NUMBER',
      'COMPANY_REP1',
      'COMPANY_REP2'

        ];
    }

}
